const fs = require('fs');
const path = require('path');

const dirs = [
  path.join(__dirname, 'app'),
  path.join(__dirname, 'components')
];

function processDir(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (let entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      processDir(fullPath);
    } else if (fullPath.endsWith('.tsx') || fullPath.endsWith('.ts')) {
      let content = fs.readFileSync(fullPath, 'utf8');
      const originalContent = content;

      // Layout Specific Fixes
      if (fullPath.includes('layout.tsx')) {
         content = content.replace(/<aside className="[^"]*bg-background[^"]*"/, (match) => match.replace('bg-background', 'bg-card'));
         content = content.replace(/<header className="[^"]*bg-background[^"]*"/, (match) => match.replace('bg-background', 'bg-card'));
         content = content.replace(/hover:bg-secondary/g, 'hover:bg-muted');
         // Icons should just inherit text color in sidebars, so we remove the explicit color on the icon if it's there
         content = content.replace(/isActive \? "text-foreground" : "text-muted-foreground\/70"/g, '""');
         content = content.replace(/className={cn\("w-5 h-5", ""\)}/g, 'className="w-5 h-5 text-current"');
      }

      // Tables
      // If we see a table structure, we need to enforce the classes
      // wrapper: bg-card border border-border rounded-xl overflow-hidden
      content = content.replace(/<div className="[^"]*overflow-x-auto[^"]*"/g, (match) => {
          if (!match.includes('bg-card')) {
             return match.replace(/className="/, 'className="bg-card border border-border rounded-xl overflow-hidden ');
          }
          return match;
      });
      content = content.replace(/<thead className="[^"]*"/g, '<thead className="bg-muted text-muted-foreground text-xs font-semibold uppercase tracking-wide"');
      content = content.replace(/<thead(?:(?!\sclassName).)*>/g, '<thead className="bg-muted text-muted-foreground text-xs font-semibold uppercase tracking-wide">');
      content = content.replace(/<tr className="[^"]*"/g, (match) => {
          if (!match.includes('border-b') && !match.includes('border-border')) {
             return match.replace(/className="/, 'className="border-b border-border hover:bg-muted/50 transition-colors ');
          }
          // if it has border-b but not our exact hover, let's just make it right
          if (match.includes('border-b')) {
              let newMatch = match.replace(/border-gray-[0-9]+/, 'border-border');
              newMatch = newMatch.replace(/hover:bg-gray-[0-9]+\/?[0-9]*/, 'hover:bg-muted/50');
              newMatch = newMatch.replace(/hover:bg-muted(?!\/)/, 'hover:bg-muted/50');
              return newMatch;
          }
          return match;
      });

      // Status Badges
      // Replace hardcoded success/fail/pending spans
      // Passed / Hired
      content = content.replace(/className="[^"]*text-green-[^"]*"/g, 'className="px-2.5 py-0.5 rounded-full text-xs font-medium bg-emerald-500/10 text-emerald-600 border border-emerald-500/20"');
      content = content.replace(/className="[^"]*text-emerald-[^"]*"/g, 'className="px-2.5 py-0.5 rounded-full text-xs font-medium bg-emerald-500/10 text-emerald-600 border border-emerald-500/20"');
      // Failed / Rejected
      content = content.replace(/className="[^"]*text-red-[^"]*"/g, 'className="px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-500/10 text-red-600 border border-red-500/20"');
      // Pending
      content = content.replace(/className="[^"]*text-yellow-[^"]*"/g, 'className="badge-subtle"');
      content = content.replace(/className="[^"]*text-orange-[^"]*"/g, 'className="badge-subtle"');

      // General badge sweep
      content = content.replace(/bg-gray-100 text-gray-600/g, 'badge-subtle');
      content = content.replace(/bg-gray-200 text-gray-700/g, 'badge-subtle');
      content = content.replace(/bg-muted\/60 text-muted-foreground/g, 'badge-subtle');

      // AI Badges sweep for actual text
      content = content.replace(/<span[^>]*>(?:AI Score|AI Analysis|AI Match|Generated by AI)[^<]*<\/span>/gi, (match) => {
          return match.replace(/className="[^"]*"/, 'className="badge-ai"');
      });

      // Buttons (sweep remaining blue)
      content = content.replace(/bg-blue-[56]00/g, 'bg-primary');
      content = content.replace(/hover:bg-blue-700/g, 'hover:brightness-110');
      content = content.replace(/text-blue-[56]00/g, 'text-primary');

      // If ghost buttons were using bg-secondary or bg-white with border
      content = content.replace(/className="[^"]*variant="outline"[^"]*"/g, (match) => {
         return match.replace(/bg-white/g, 'bg-transparent').replace(/hover:bg-gray-50/g, 'hover:bg-muted').replace(/text-gray-700/g, 'text-foreground').replace(/border-gray-200/g, 'border-border');
      });

      if (content !== originalContent) {
        fs.writeFileSync(fullPath, content, 'utf8');
        console.log('Updated: ' + fullPath);
      }
    }
  }
}

dirs.forEach(processDir);
console.log('Done!');
